name: quynhvng

baseurl: /
url: https://quynhvng.github.io
permalink: /blog/:year/:month/:day/:title

markdown: kramdown
plugins:
  - jekyll-sitemap

collections_dir: collections
collections:
  portfolio:
    output: true